// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightingControlService.proto

package ds.lightingControlService;

public final class LightingControlServiceImpl {
  private LightingControlServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightingControlService_SwitchLightOnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightingControlService_SwitchLightOnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightingControlService_SwitchLightOnResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightingControlService_SwitchLightOnResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightingControlService_SwitchLightOffRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightingControlService_SwitchLightOffRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightingControlService_SwitchLightOffResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightingControlService_SwitchLightOffResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightingControlService_SetTimeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightingControlService_SetTimeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightingControlService_SetTimeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightingControlService_SetTimeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034lightingControlService.proto\022\026lighting" +
      "ControlService\"\'\n\024SwitchLightOnRequest\022\017" +
      "\n\007detects\030\001 \001(\010\"\'\n\025SwitchLightOnResponse" +
      "\022\016\n\006status\030\001 \001(\t\"(\n\025SwitchLightOffReques" +
      "t\022\017\n\007detects\030\001 \001(\010\"(\n\026SwitchLightOffResp" +
      "onse\022\016\n\006status\030\001 \001(\t\"\036\n\016SetTimeRequest\022\014" +
      "\n\004time\030\001 \001(\002\"!\n\017SetTimeResponse\022\016\n\006statu" +
      "s\030\001 \001(\t2\344\002\n\026LightingControlService\022n\n\rsw" +
      "itchLightOn\022,.lightingControlService.Swi" +
      "tchLightOnRequest\032-.lightingControlServi" +
      "ce.SwitchLightOnResponse\"\000\022q\n\016switchLigh" +
      "tOff\022-.lightingControlService.SwitchLigh" +
      "tOffRequest\032..lightingControlService.Swi" +
      "tchLightOffResponse\"\000\022g\n\022setSwitchLightT" +
      "ime\022&.lightingControlService.SetTimeRequ" +
      "est\032\'.lightingControlService.SetTimeResp" +
      "onse\"\000B9\n\031ds.lightingControlServiceB\032Lig" +
      "htingControlServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_lightingControlService_SwitchLightOnRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lightingControlService_SwitchLightOnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightingControlService_SwitchLightOnRequest_descriptor,
        new java.lang.String[] { "Detects", });
    internal_static_lightingControlService_SwitchLightOnResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lightingControlService_SwitchLightOnResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightingControlService_SwitchLightOnResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_lightingControlService_SwitchLightOffRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lightingControlService_SwitchLightOffRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightingControlService_SwitchLightOffRequest_descriptor,
        new java.lang.String[] { "Detects", });
    internal_static_lightingControlService_SwitchLightOffResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_lightingControlService_SwitchLightOffResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightingControlService_SwitchLightOffResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_lightingControlService_SetTimeRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_lightingControlService_SetTimeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightingControlService_SetTimeRequest_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_lightingControlService_SetTimeResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_lightingControlService_SetTimeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightingControlService_SetTimeResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
