// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightingControlService.proto

package ds.lightingControlService;

public interface SetTimeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightingControlService.SetTimeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float time = 1;</code>
   */
  float getTime();
}
