// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightingControlService.proto

package ds.lightingControlService;

public interface SwitchLightOnRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightingControlService.SwitchLightOnRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool detects = 1;</code>
   */
  boolean getDetects();
}
