// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightingControlService.proto

package ds.lightingControlService;

public interface SwitchLightOffResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightingControlService.SwitchLightOffResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
