// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperatureControlService.proto

package ds.temperatureControlService;

public interface GetTemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperatureControlService.GetTemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestValue = 1;</code>
   */
  java.lang.String getRequestValue();
  /**
   * <code>string requestValue = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestValueBytes();
}
