// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperatureControlService.proto

package ds.temperatureControlService;

public interface GetTemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperatureControlService.GetTemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float getValue = 1;</code>
   */
  float getGetValue();
}
