// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperatureControlService.proto

package ds.temperatureControlService;

public interface SetTemperatureTimeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperatureControlService.SetTemperatureTimeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
