// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperatureControlService.proto

package ds.temperatureControlService;

public interface SetTemperatureTimeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperatureControlService.SetTemperatureTimeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float time = 1;</code>
   */
  float getTime();
}
