// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperatureControlService.proto

package ds.temperatureControlService;

public interface SetTemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperatureControlService.SetTemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float value = 1;</code>
   */
  float getValue();
}
