// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperatureControlService.proto

package ds.temperatureControlService;

public final class TemperatureControlServiceImpl {
  private TemperatureControlServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_temperatureControlService_SetTemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_temperatureControlService_SetTemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_temperatureControlService_SetTemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_temperatureControlService_SetTemperatureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_temperatureControlService_GetTemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_temperatureControlService_GetTemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_temperatureControlService_GetTemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_temperatureControlService_GetTemperatureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_temperatureControlService_SetTemperatureTimeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_temperatureControlService_SetTemperatureTimeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_temperatureControlService_SetTemperatureTimeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_temperatureControlService_SetTemperatureTimeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037temperatureControlService.proto\022\031tempe" +
      "ratureControlService\"&\n\025SetTemperatureRe" +
      "quest\022\r\n\005value\030\001 \001(\002\"(\n\026SetTemperatureRe" +
      "sponse\022\016\n\006status\030\001 \001(\t\"-\n\025GetTemperature" +
      "Request\022\024\n\014requestValue\030\001 \001(\t\"*\n\026GetTemp" +
      "eratureResponse\022\020\n\010getValue\030\001 \001(\002\")\n\031Set" +
      "TemperatureTimeRequest\022\014\n\004time\030\001 \001(\002\",\n\032" +
      "SetTemperatureTimeResponse\022\016\n\006status\030\001 \001" +
      "(\t2\223\003\n\031TemperatureControlService\022w\n\016setT" +
      "emperature\0220.temperatureControlService.S" +
      "etTemperatureRequest\0321.temperatureContro" +
      "lService.SetTemperatureResponse\"\000\022w\n\016get" +
      "Temperature\0220.temperatureControlService." +
      "GetTemperatureRequest\0321.temperatureContr" +
      "olService.GetTemperatureResponse\"\000\022\203\001\n\022s" +
      "etTemperatureTime\0224.temperatureControlSe" +
      "rvice.SetTemperatureTimeRequest\0325.temper" +
      "atureControlService.SetTemperatureTimeRe" +
      "sponse\"\000B?\n\034ds.temperatureControlService" +
      "B\035TemperatureControlServiceImplP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_temperatureControlService_SetTemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_temperatureControlService_SetTemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_temperatureControlService_SetTemperatureRequest_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_temperatureControlService_SetTemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_temperatureControlService_SetTemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_temperatureControlService_SetTemperatureResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_temperatureControlService_GetTemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_temperatureControlService_GetTemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_temperatureControlService_GetTemperatureRequest_descriptor,
        new java.lang.String[] { "RequestValue", });
    internal_static_temperatureControlService_GetTemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_temperatureControlService_GetTemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_temperatureControlService_GetTemperatureResponse_descriptor,
        new java.lang.String[] { "GetValue", });
    internal_static_temperatureControlService_SetTemperatureTimeRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_temperatureControlService_SetTemperatureTimeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_temperatureControlService_SetTemperatureTimeRequest_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_temperatureControlService_SetTemperatureTimeResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_temperatureControlService_SetTemperatureTimeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_temperatureControlService_SetTemperatureTimeResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
