// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecurityControlService.proto

package ds.securityControlService;

/**
 * Protobuf type {@code securityControlService.DeactivateAlarmRequest}
 */
public  final class DeactivateAlarmRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:securityControlService.DeactivateAlarmRequest)
    DeactivateAlarmRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeactivateAlarmRequest.newBuilder() to construct.
  private DeactivateAlarmRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeactivateAlarmRequest() {
    doorId_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DeactivateAlarmRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            doorId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.securityControlService.SecurityControlServiceImpl.internal_static_securityControlService_DeactivateAlarmRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.securityControlService.SecurityControlServiceImpl.internal_static_securityControlService_DeactivateAlarmRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.securityControlService.DeactivateAlarmRequest.class, ds.securityControlService.DeactivateAlarmRequest.Builder.class);
  }

  public static final int DOORID_FIELD_NUMBER = 1;
  private int doorId_;
  /**
   * <code>int32 doorId = 1;</code>
   */
  public int getDoorId() {
    return doorId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (doorId_ != 0) {
      output.writeInt32(1, doorId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (doorId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, doorId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.securityControlService.DeactivateAlarmRequest)) {
      return super.equals(obj);
    }
    ds.securityControlService.DeactivateAlarmRequest other = (ds.securityControlService.DeactivateAlarmRequest) obj;

    boolean result = true;
    result = result && (getDoorId()
        == other.getDoorId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DOORID_FIELD_NUMBER;
    hash = (53 * hash) + getDoorId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.securityControlService.DeactivateAlarmRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.securityControlService.DeactivateAlarmRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.securityControlService.DeactivateAlarmRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.securityControlService.DeactivateAlarmRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.securityControlService.DeactivateAlarmRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.securityControlService.DeactivateAlarmRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.securityControlService.DeactivateAlarmRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.securityControlService.DeactivateAlarmRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.securityControlService.DeactivateAlarmRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.securityControlService.DeactivateAlarmRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.securityControlService.DeactivateAlarmRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.securityControlService.DeactivateAlarmRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.securityControlService.DeactivateAlarmRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code securityControlService.DeactivateAlarmRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:securityControlService.DeactivateAlarmRequest)
      ds.securityControlService.DeactivateAlarmRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.securityControlService.SecurityControlServiceImpl.internal_static_securityControlService_DeactivateAlarmRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.securityControlService.SecurityControlServiceImpl.internal_static_securityControlService_DeactivateAlarmRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.securityControlService.DeactivateAlarmRequest.class, ds.securityControlService.DeactivateAlarmRequest.Builder.class);
    }

    // Construct using ds.securityControlService.DeactivateAlarmRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      doorId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.securityControlService.SecurityControlServiceImpl.internal_static_securityControlService_DeactivateAlarmRequest_descriptor;
    }

    @java.lang.Override
    public ds.securityControlService.DeactivateAlarmRequest getDefaultInstanceForType() {
      return ds.securityControlService.DeactivateAlarmRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ds.securityControlService.DeactivateAlarmRequest build() {
      ds.securityControlService.DeactivateAlarmRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.securityControlService.DeactivateAlarmRequest buildPartial() {
      ds.securityControlService.DeactivateAlarmRequest result = new ds.securityControlService.DeactivateAlarmRequest(this);
      result.doorId_ = doorId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.securityControlService.DeactivateAlarmRequest) {
        return mergeFrom((ds.securityControlService.DeactivateAlarmRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.securityControlService.DeactivateAlarmRequest other) {
      if (other == ds.securityControlService.DeactivateAlarmRequest.getDefaultInstance()) return this;
      if (other.getDoorId() != 0) {
        setDoorId(other.getDoorId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.securityControlService.DeactivateAlarmRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.securityControlService.DeactivateAlarmRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int doorId_ ;
    /**
     * <code>int32 doorId = 1;</code>
     */
    public int getDoorId() {
      return doorId_;
    }
    /**
     * <code>int32 doorId = 1;</code>
     */
    public Builder setDoorId(int value) {
      
      doorId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 doorId = 1;</code>
     */
    public Builder clearDoorId() {
      
      doorId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:securityControlService.DeactivateAlarmRequest)
  }

  // @@protoc_insertion_point(class_scope:securityControlService.DeactivateAlarmRequest)
  private static final ds.securityControlService.DeactivateAlarmRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.securityControlService.DeactivateAlarmRequest();
  }

  public static ds.securityControlService.DeactivateAlarmRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeactivateAlarmRequest>
      PARSER = new com.google.protobuf.AbstractParser<DeactivateAlarmRequest>() {
    @java.lang.Override
    public DeactivateAlarmRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DeactivateAlarmRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DeactivateAlarmRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeactivateAlarmRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.securityControlService.DeactivateAlarmRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

