// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecurityControlService.proto

package ds.securityControlService;

public interface LockDoorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:securityControlService.LockDoorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
