// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecurityControlService.proto

package ds.securityControlService;

public interface LockDoorStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:securityControlService.LockDoorStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string doorIdRequest = 1;</code>
   */
  java.lang.String getDoorIdRequest();
  /**
   * <code>string doorIdRequest = 1;</code>
   */
  com.google.protobuf.ByteString
      getDoorIdRequestBytes();
}
