// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecurityControlService.proto

package ds.securityControlService;

public final class SecurityControlServiceImpl {
  private SecurityControlServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_securityControlService_LockDoorStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_securityControlService_LockDoorStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_securityControlService_LockDoorStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_securityControlService_LockDoorStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_securityControlService_UnlockDoorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_securityControlService_UnlockDoorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_securityControlService_UnlockDoorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_securityControlService_UnlockDoorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_securityControlService_LockDoorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_securityControlService_LockDoorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_securityControlService_LockDoorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_securityControlService_LockDoorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_securityControlService_ActivateAlarmRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_securityControlService_ActivateAlarmRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_securityControlService_ActivateAlarmResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_securityControlService_ActivateAlarmResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_securityControlService_DeactivateAlarmRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_securityControlService_DeactivateAlarmRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_securityControlService_DeactivateAlarmResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_securityControlService_DeactivateAlarmResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034SecurityControlService.proto\022\026security" +
      "ControlService\".\n\025LockDoorStatusRequest\022" +
      "\025\n\rdoorIdRequest\030\001 \001(\t\"(\n\026LockDoorStatus" +
      "Response\022\016\n\006status\030\001 \001(\t\"#\n\021UnlockDoorRe" +
      "quest\022\016\n\006doorId\030\001 \001(\005\"$\n\022UnlockDoorRespo" +
      "nse\022\016\n\006status\030\001 \001(\t\"!\n\017LockDoorRequest\022\016" +
      "\n\006doorId\030\001 \001(\005\"\"\n\020LockDoorResponse\022\016\n\006st" +
      "atus\030\001 \001(\t\"&\n\024ActivateAlarmRequest\022\016\n\006do" +
      "orId\030\001 \001(\005\"\'\n\025ActivateAlarmResponse\022\016\n\006s" +
      "tatus\030\001 \001(\t\"(\n\026DeactivateAlarmRequest\022\016\n" +
      "\006doorId\030\001 \001(\005\")\n\027DeactivateAlarmResponse" +
      "\022\016\n\006status\030\001 \001(\t2\301\007\n\026SecurityControlServ" +
      "ice\022e\n\nunlockDoor\022).securityControlServi" +
      "ce.UnlockDoorRequest\032*.securityControlSe" +
      "rvice.UnlockDoorResponse\"\000\022_\n\010lockDoor\022\'" +
      ".securityControlService.LockDoorRequest\032" +
      "(.securityControlService.LockDoorRespons" +
      "e\"\000\022n\n\ractivateAlarm\022,.securityControlSe" +
      "rvice.ActivateAlarmRequest\032-.securityCon" +
      "trolService.ActivateAlarmResponse\"\000\022t\n\017d" +
      "eactivateAlarm\022..securityControlService." +
      "DeactivateAlarmRequest\032/.securityControl" +
      "Service.DeactivateAlarmResponse\"\000\022~\n\031get" +
      "LockStatusServerStream\022-.securityControl" +
      "Service.LockDoorStatusRequest\032..security" +
      "ControlService.LockDoorStatusResponse\"\0000" +
      "\001\022|\n\031activateAlarmClientStream\022,.securit" +
      "yControlService.ActivateAlarmRequest\032-.s" +
      "ecurityControlService.ActivateAlarmRespo" +
      "nse\"\000(\001\022\202\001\n\033deactivateAlarmClientStream\022" +
      "..securityControlService.DeactivateAlarm" +
      "Request\032/.securityControlService.Deactiv" +
      "ateAlarmResponse\"\000(\001\022v\n\033lockDoorBidirect" +
      "ionalStream\022\'.securityControlService.Loc" +
      "kDoorRequest\032(.securityControlService.Lo" +
      "ckDoorResponse\"\000(\0010\001B9\n\031ds.securityContr" +
      "olServiceB\032SecurityControlServiceImplP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_securityControlService_LockDoorStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_securityControlService_LockDoorStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_securityControlService_LockDoorStatusRequest_descriptor,
        new java.lang.String[] { "DoorIdRequest", });
    internal_static_securityControlService_LockDoorStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_securityControlService_LockDoorStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_securityControlService_LockDoorStatusResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_securityControlService_UnlockDoorRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_securityControlService_UnlockDoorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_securityControlService_UnlockDoorRequest_descriptor,
        new java.lang.String[] { "DoorId", });
    internal_static_securityControlService_UnlockDoorResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_securityControlService_UnlockDoorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_securityControlService_UnlockDoorResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_securityControlService_LockDoorRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_securityControlService_LockDoorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_securityControlService_LockDoorRequest_descriptor,
        new java.lang.String[] { "DoorId", });
    internal_static_securityControlService_LockDoorResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_securityControlService_LockDoorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_securityControlService_LockDoorResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_securityControlService_ActivateAlarmRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_securityControlService_ActivateAlarmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_securityControlService_ActivateAlarmRequest_descriptor,
        new java.lang.String[] { "DoorId", });
    internal_static_securityControlService_ActivateAlarmResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_securityControlService_ActivateAlarmResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_securityControlService_ActivateAlarmResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_securityControlService_DeactivateAlarmRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_securityControlService_DeactivateAlarmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_securityControlService_DeactivateAlarmRequest_descriptor,
        new java.lang.String[] { "DoorId", });
    internal_static_securityControlService_DeactivateAlarmResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_securityControlService_DeactivateAlarmResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_securityControlService_DeactivateAlarmResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
