// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecurityControlService.proto

package ds.securityControlService;

public interface UnlockDoorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:securityControlService.UnlockDoorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 doorId = 1;</code>
   */
  int getDoorId();
}
